version: '{build}'
skip_tags: true
clone_depth: 10
branches:
  only:
    - master
  except:
    - gh-pages
os: Windows Server 2012
environment:
  matrix:
    - ruby_version: "25-x64"
install:
  - ps: |
      $Env:PATH = "C:\Ruby${Env:ruby_version}\bin;${Env:PATH}"
      if ($Env:ruby_version -match "^23" ) {
        # RubyInstaller; download OpenSSL headers from OpenKnapsack Project
        $Env:openssl_dir = "C:\Ruby${Env:ruby_version}"
        appveyor DownloadFile http://dl.bintray.com/oneclick/OpenKnapsack/x64/openssl-1.0.2j-x64-windows.tar.lzma
        7z e openssl-1.0.2j-x64-windows.tar.lzma
        7z x -y -oC:\Ruby${Env:ruby_version} openssl-1.0.2j-x64-windows.tar
      } else {
        # RubyInstaller2; openssl package seems to be installed already
        $Env:openssl_dir = "C:\msys64\mingw64"
      }
  - bundle config --local path vendor/bundle

  # Download & extract libcurl
  # Copy libcurl.{dll,lib} and add to PATH, so that libcurl.dll is found during the tests
  - ps: |
        appveyor DownloadFile "https://dl.dropboxusercontent.com/s/jxwohqax4e2avyt/libcurl-7.48.0-WinSSL-zlib-x86-x64.zip?dl=0" -FileName libcurl.zip
        7z x libcurl.zip
        cp dmd2\windows\bin64\libcurl.dll C:\Ruby${Env:ruby_version}\bin
        cp dmd2\windows\lib64\curl.lib C:\Ruby${Env:ruby_version}\bin

  - bundle config build.openssl --with-openssl-dir=%openssl_dir%
  - ruby -v
  - bundle -v
build_script:
  - bundle update
  - bundle install
test_script:
  - bundle exec rake --quiet
cache:
  - vendor/bundle
